name: CI/CD Branche Develop
on:
    push:
        branches:
            - develop

jobs:
    counter_push:
        runs-on: ubuntu-latest
        steps:
            - name: Initialisation
              run: |
                  echo retour branche develop OK
